tap "alecthomas/tap"
tap "golangci/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/php"
tap "homebrew/services"
brew "ascii"
brew "autoconf"
brew "automake"
brew "gdbm"
brew "openssl"
brew "readline"
brew "sqlite"
brew "python"
brew "awscli"
brew "bash-completion"
brew "bat"
brew "bind", restart_service: true
brew "gettext"
brew "pcre"
brew "glib"
brew "pixman"
brew "cairo"
brew "clang-format"
brew "colordiff"
brew "composer"
brew "curl"
brew "icu4c"
brew "node"
brew "eslint"
brew "exa"
brew "exiftags"
brew "fribidi"
brew "libunistring"
brew "harfbuzz"
brew "libtiff"
brew "little-cms2"
brew "webp"
brew "rtmpdump"
brew "ffmpeg"
brew "fswatch"
brew "gd"
brew "git"
brew "go"
brew "graphviz"
brew "hyperfine"
brew "id3v2"
brew "imagemagick"
brew "oniguruma"
brew "jq"
brew "libidn2"
brew "libmagic"
brew "libyaml"
brew "lnav"
brew "mas"
brew "mkcert"
brew "youtube-dl"
brew "mpv"
brew "nmap"
brew "pandoc"
brew "perl"
brew "php-code-sniffer"
brew "prettier"
brew "python@2"
brew "protobuf"
brew "pup"
brew "qrencode"
brew "ruby", link: true
brew "rust"
brew "shellcheck"
brew "shfmt"
brew "terminal-notifier"
brew "tokei"
brew "tree"
brew "vegeta"
brew "vnstat", restart_service: true
brew "wget"
brew "wrk"
brew "yuicompressor"
brew "alecthomas/tap/gometalinter"
brew "golangci/tap/golangci-lint"
cask "1password"
cask "android-file-transfer"
cask "basictex"
cask "bit-slicer"
cask "bitbar"
cask "burp-suite"
cask "coderunner"
cask "cornerstone"
cask "couleurs"
cask "dash3"
cask "deckset"
cask "docker"
cask "expressions"
cask "gifox"
cask "gpg-suite"
cask "grammarly"
cask "hex-fiend"
cask "hider"
cask "hopper-disassembler"
cask "imageoptim"
cask "insomnia"
cask "iterm2"
cask "kaleidoscope"
cask "little-snitch"
cask "monodraw"
cask "ngrok"
cask "nordvpn"
cask "oclint"
cask "openemu"
cask "paparazzi"
cask "paw"
cask "platypus"
cask "poedit"
cask "postico"
cask "pusher"
cask "qbserve"
cask "screentray"
cask "sequel-pro"
cask "sketch"
cask "slack"
cask "sloth"
cask "sourcetree"
cask "spectacle"
cask "steam"
cask "sublime-merge"
cask "sublime-text-dev"
cask "synalyze-it-pro"
cask "table-tool"
cask "tableedit"
cask "tableplus"
cask "tor-browser"
cask "transmission"
cask "whatsapp"
cask "wireshark"
mas "Encrypto", id: 935235287
mas "GarageBand", id: 682658836
mas "GIF Brewery 3", id: 1081413713
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Marko", id: 607997198
mas "Money", id: 1185488696
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Profiling Viewer", id: 1079647046
mas "Proxie", id: 897814548
mas "Reeder", id: 880001334
mas "Xcode", id: 497799835
