#!/bin/bash
# Disguise CURL as a normal web browser
curl -H 'DNT: 1' \
-H 'Pragma: no-cache' \
-H 'Upgrade-Insecure-Requests: 1' \
-H 'Accept-Language: en-US,en;q=0.8' \
-H 'Accept-Encoding: gzip, deflate, sdch, br' \
-H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12' \
-H 'Cache-Control: no-cache' \
-H 'Connection: keep-alive' \
--compressed "$@"
