#!/bin/bash
if [[ "$1" == "" ]]; then
    SCRIPT=$(basename "$0")
    echo "Camelcase"
    echo
    echo "Camel case (stylized as camelCase or CamelCase; also known as camel caps"
    echo "or more formally as medial capitals) is the practice of writing compound"
    echo "words or phrases such that each word or abbreviation in the middle of"
    echo "the phrase begins with a capital letter, with no intervening spaces or"
    echo "punctuation."
    echo
    echo "Usage:"
    echo "  ${SCRIPT} lorem_ipsum_dolor";
    echo "  ${SCRIPT} LOrem-ipSUM_dOLor";
    exit 2
fi

RESULT=""
COUNTER=0
WORDS="${1:-foobar}"
WORDS=$(echo "$WORDS" | sed "s/_/ /g")
WORDS=$(echo "$WORDS" | sed "s/-/ /g")

for WORD in $WORDS; do
    FIRST=$(echo "$WORD" | cut -c1 | tr "[:lower:]" "[:upper:]")
    OTHERS=$(echo "$WORD" | cut -c2-1000 | tr "[:upper:]" "[:lower:]")
    if [[ "$COUNTER" -eq 0 ]]; then
        FIRST=$(echo "$FIRST" | tr "[:upper:]" "[:lower:]")
    fi
    RESULT+="${FIRST}${OTHERS}"
    COUNTER=$((COUNTER + 1))
done

echo "$RESULT"
