#!/bin/bash
#
# CodeEval
# https://cixtor.com/
# https://www.codeeval.com/
#
# CodeEval is a platform used by developers to showcase their skills. Developers
# can participate in app building competitions and win cash/prizes. They can also
# solve programming challenges as a way to impress employers with their technical
# skills. Employers can use CodeEval as a way to enhance their brand by launching
# competitions/programming challenges and as a means to get introduced to the best
# developers.
#
IFS=$'\n'

if [[ "$1" == "" ]] || [[ "$1" =~ help ]]; then
    S=$(echo "$0" | rev | cut -d/ -f 1 | rev)
    echo "CodeEval Solution Checker"
    echo "  https://cixtor.com/"
    echo "  https://www.codeeval.com/"
    echo "  https://en.wikipedia.org/wiki/Competitive_programming"
    echo "Usage:"
    echo "  $S [challenge.ext] [-debug]"
    echo "  $S solution.cpp -new [name] Creates new challenge"
    echo "  $S solution.cpp -debug      Prints all unit-tests"
    echo "  $S solution.go              Executes all unit-tests"
    exit 1
fi

EXEC_COMMAND="null"
SOLUTION_FILE="$1"
DEBUG_UNIT_TEST="$2"
TEMP_INPUT_FILE='temp.input.txt'
UNIT_TEST_FILE='temp.unittest.php'
PHPUNIT_BIN="/usr/local/bin/phpunit"
EXTENSION=$(echo "${SOLUTION_FILE}" | rev | cut -d. -f1 | rev)

if [[ "$1" == "-new" ]]; then
    if [[ "$2" == "" ]]; then
        echo "Challenge name is missing"
        exit 1
    fi

    if [[ -e "$2" ]]; then
        echo "Directory already exists"
        exit 1
    fi

    CODE=""
    NAME="$2"

    mkdir -pv -- "$NAME" 2> /dev/null
    touch -- "${NAME}/input.txt"
    touch -- "${NAME}/output.txt"

    CODE+="cGFja2FnZSBtYWluCgppbXBvcnQgKAoJImJ1ZmlvIgoJImZtdCIKCSJvcyIKCSJzdHJjb252IgoJInN0"
    CODE+="cmluZ3MiCikKCmZ1bmMgc29sdXRpb24ocGFydHMgW11zdHJpbmcpIHN0cmluZyB7CglyZXR1cm4gIiIK"
    CODE+="fQoKZnVuYyBtYWluKCkgewoJZmlsZSwgZXJyIDo9IG9zLk9wZW4ob3MuQXJnc1sxXSkKCglpZiBlcnIg"
    CODE+="IT0gbmlsIHsKCQlwYW5pYyhlcnIpCgl9CgoJdmFyIGxpbmUgc3RyaW5nCgl2YXIgcGFydHMgW11zdHJp"
    CODE+="bmcKCglzY2FubmVyIDo9IGJ1ZmlvLk5ld1NjYW5uZXIoZmlsZSkKCglmb3Igc2Nhbm5lci5TY2FuKCkg"
    CODE+="ewoJCWxpbmUgPSBzY2FubmVyLlRleHQoKQoJCXBhcnRzID0gc3RyaW5ncy5TcGxpdChsaW5lLCAiOyIp"
    CODE+="CgoJCWZtdC5QcmludGxuKHNvbHV0aW9uKHBhcnRzKSkKCX0KfQo="

    echo "$CODE" | base64 -D 1> "${NAME}/solution.go"
    echo "cd ${NAME} && $0 solution.go"
    exit
fi

case "$EXTENSION" in
    'cpp' ) EXEC_COMMAND="g++ -o test.bin ${SOLUTION_FILE} && ./test.bin %s && rm test.bin";;
    'swift' ) EXEC_COMMAND="swiftc -o test.bin ${SOLUTION_FILE} && ./test.bin %s && rm test.bin";;
    'go' ) EXEC_COMMAND="go run ${SOLUTION_FILE} %s";;
    'sh' ) EXEC_COMMAND="bash ${SOLUTION_FILE} %s";;
    'rb' ) EXEC_COMMAND="ruby ${SOLUTION_FILE} %s";;
    'py' ) EXEC_COMMAND="python3 ${SOLUTION_FILE} %s";;
    'php' ) EXEC_COMMAND="php -f ${SOLUTION_FILE} %s";;
esac

if [[ "$EXEC_COMMAND" == "null" ]]; then
    echo "Language is not supported: ${EXTENSION}"
    exit 1
fi

if [[ ! -e "input.txt" ]]; then
    echo "Input file is missing: input.txt"
    exit 1
fi

if [[ ! -e "output.txt" ]]; then
    echo "Output file is missing: output.txt"
    exit 1
fi

if [[ "$PHPUNIT_BIN" == "" ]]; then
    echo "PHPUnit was not found — https://phpunit.de/"
    exit 1
fi

INPUT_VALUES=()
OUTPUT_VALUES=()
while read -r LINE; do INPUT_VALUES+=("$LINE"); done < input.txt
while read -r LINE; do OUTPUT_VALUES+=("$LINE"); done < output.txt

TOTAL_CASES="${#INPUT_VALUES[@]}"

PHP_CODE="" # Holds the PHPUnit test cases.
PHP_CODE+="<?php\n"
PHP_CODE+="function s(\$text = '') {\n"
PHP_CODE+="  \$input = '$TEMP_INPUT_FILE';\n"
PHP_CODE+="  \$text = base64_decode(\$text);\n"
PHP_CODE+="  \$command = sprintf('$EXEC_COMMAND', \$input);\n"
PHP_CODE+="  file_put_contents(\$input, \$text, LOCK_EX);\n"
PHP_CODE+="  return exec(\$command);\n"
PHP_CODE+="}\n"
PHP_CODE+="class CodeEvalTest extends PHPUnit_Framework_TestCase {\n"
for (( KEY=0; KEY<TOTAL_CASES; KEY++ )); do
    INPUTSTR=$(echo "${INPUT_VALUES[KEY]}" | base64 | tr -d '\n')
    EXPECTED=$(echo "${OUTPUT_VALUES[KEY]}" | sed "s/'/\\\'/g")
    PHP_CODE+="  public function test_codeeval_case_${KEY}() {\n"
    PHP_CODE+="    \$this->assertEquals('$EXPECTED', s('${INPUTSTR}'));\n"
    PHP_CODE+="  }\n"
done
PHP_CODE+="}"

# Write PHP code into the test file.
echo -e "$PHP_CODE" > "$UNIT_TEST_FILE"

# Print the content of the test file if necessary.
if [[ "$DEBUG_UNIT_TEST" == "-debug" ]]; then
    cat "$UNIT_TEST_FILE" && exit 0
fi

# Execute the test file using the PHPUnit tool.
eval "$PHPUNIT_BIN --color $UNIT_TEST_FILE"
rm -fv -- "$UNIT_TEST_FILE"
rm -fv -- "$TEMP_INPUT_FILE"
exit 0
