#!/bin/bash

echo -n "Full Name: "; read -r FULLNAME;
echo -n "Phone (1st): "; read -r PHONE_FIRST;
echo -n "Phone (2nd): "; read -r PHONE_SECOND;
echo -n "Phone (3rd): "; read -r PHONE_THIRD;
echo -n "E-mail: "; read -r EMAIL;
echo -n "Picture: "; read -r PICTURE;
echo -n "Website: "; read -r WEBSITE;
echo -n "Notes: "; read -r NOTES;
echo -n "Address (y/n)? "; read -r HAVE_ADDRESS;

if [[ "$HAVE_ADDRESS" == "y" ]]; then
    echo -n "Address Street (123 Foobar St.): "; read -r ADDRESS_STREET;
    echo -n "Address City (Vancouver): "; read -r ADDRESS_CITY;
    echo -n "Address State (BC): "; read -r ADDRESS_STATE;
    echo -n "Address Country (Canada): "; read -r ADDRESS_COUNTRY;
    echo -n "Address Postal Code (V6Z 2Y1): "; read -r ADDRESS_POSTAL_CODE;
fi

STORAGE=$(printf "BEGIN:VCARD")
STORAGE+=$(printf "\nVERSION:3.0")
STORAGE+=$(printf "\nFN:%s" "$FULLNAME")

if [[ "$PHONE_FIRST" != "" ]]; then
    STORAGE+=$(printf "\nTEL;TYPE=CELL:%s" "$PHONE_FIRST")
fi

if [[ "$PHONE_SECOND" != "" ]]; then
    STORAGE+=$(printf "\nTEL;TYPE=WORK:%s" "$PHONE_SECOND")
fi

if [[ "$PHONE_THIRD" != "" ]]; then
    STORAGE+=$(printf "\nTEL;TYPE=HOME:%s" "$PHONE_THIRD")
fi

if [[ "$EMAIL" != "" ]]; then
    STORAGE+=$(printf "\nEMAIL:%s" "$EMAIL")
fi

if [[ "$HAVE_ADDRESS" == "y" ]]; then
    STORAGE+=$(printf "\nADR;TYPE=HOME:;;%s;%s;%s;%s;%s" "$ADDRESS_STREET" "$ADDRESS_CITY" "$ADDRESS_STATE" "$ADDRESS_POSTAL_CODE" "$ADDRESS_COUNTRY")
fi

if [[ "$WEBSITE" != "" ]]; then
    STORAGE+=$(printf "\nURL:%s" "$WEBSITE")
fi

if [[ "$NOTES" != "" ]]; then
    NOTES=${NOTES//,/\,}
    STORAGE+=$(printf "\nNOTE:%s" "$NOTES")
fi

if [[ "$PICTURE" != "" ]]; then
    STORAGE+=$(printf "\nPHOTO;ENCODING=BASE64;TYPE=JPEG:")
    STORAGE+=$(curl "$PICTURE" -s | base64 -b 74 | sed "s/^/ /")
fi

STORAGE+=$(printf "\nEND:VCARD")

FORMAT="${FULLNAME// /_}"

echo "$STORAGE" 1> "${HOME}/Downloads/${FORMAT}.vcf"
