#!/bin/bash
# Execute a custom command on filesystem changes.
if [[ "$1" =~ help ]]; then
    SCRIPT=$(basename "$0")

    echo "Execute On..."
    echo
    echo "Usage:"
    echo "  $SCRIPT make build"
    echo "  $SCRIPT echo 'Hello World'"
    echo "  $SCRIPT rsync project pi@192.168.1.50:/var/www"
    echo
    echo "Dependencies:"
    echo "  Linux: apt-get install inotify-tools"
    echo "  Mac: brew install fswatch terminal-notifier"
    exit 2
fi

if command -v fswatch &> /dev/null; then
    COMMAND="$@"
    NOTIFICATION="echo 'Finished execution'"
    if command -v terminal-notifier &> /dev/null; then
        NOTIFICATION="terminal-notifier -message '${COMMAND}' ${RANDOM} -title 'Finished Execution' -timeout 5 &> /dev/null"
    fi
    fswatch -o . | xargs -n1 sh -c "${COMMAND} ; ${NOTIFICATION}"
    exit
fi

if command -v inotifywait &> /dev/null; then
    DIRECTORY=$(pwd)
    while inotifywait -r -e modify --format="%w%f" "$DIRECTORY"; do
        URGENCY="normal"
        if [[ "$1" != "" ]]; then
            if eval "$@"; then
                URGENCY="normal"
            else
                URGENCY="critical"
            fi
        fi
        SHORT_DIRECTORY="${DIRECTORY//$HOME/\~}"
        notify-send "Run On Change" \
        "Directory ${SHORT_DIRECTORY} has changed" \
        --urgency="$URGENCY" \
        --expire-time=2000
    done
    exit
fi
