#!/bin/bash
COMMIT="$1" # Full commit hash.
COMDATE="$2" # yyyy-mm-dd

export FILTER_BRANCH_SQUELCH_WARNING=1

if [[ "$COMMIT" == "" ]] || [[ "$COMDATE" == "" ]]; then
    SCRIPT=$(echo "$0" | rev | cut -d/ -f1 | rev)
    echo "Repository Status"
    echo "  https://cixtor.com/"
    echo "  https://en.wikipedia.org/wiki/Git"
    echo "  https://github.com/cixtor/dotfiles/.bin/"
    echo "Usage:"
    echo "  ${SCRIPT} [commit] [yyyy-mm-dd]"
    exit 2
fi

COMDATE="${COMDATE}T09:00:00"

echo "${COMMIT} - ${COMDATE}"

git filter-branch -f --env-filter \
"if [ \$GIT_COMMIT == $COMMIT ]; then
export GIT_AUTHOR_DATE='$COMDATE'
export GIT_COMMITTER_DATE='$COMDATE'
fi"
