#!/bin/bash
# Disguise CURL as the Google web crawler.
curl -H 'DNT: 1' \
-H 'Upgrade-Insecure-Requests: 1' \
-H 'Accept-Encoding: gzip, deflate' \
-H 'Accept-Language: en-US,en;q=0.8' \
-H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' \
-H 'User-Agent: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)' \
--compressed "$@"
