#!/bin/bash
# Calculate Mercurial ahead and behind commits
#
# b_sw3jdurr   3965:7f2a83ffc61d
# b_le3g3mfe   3946:b03737187a81 (inactive) ▏                19
# b_kan3g0ij   3936:8d3c665602e5 (inactive) ▎                29
# b_x0lctp54   3891:fbee645a2f0c (inactive) ▊                74
# b_ebo3bxj4   3460:fedb88847071 (inactive) █████▊           505
# b_i86f5qln   3182:2b132fa69174 (inactive) ████████▉        783
# b_0tvihibs   3065:c3bff4489ee1 (inactive) ██████████▍      900
# b_iuifnik4   3003:2d633479b952 (inactive) ███████████      962
# b_d0vkqfv0   2972:d205390198c6 (inactive) ███████████▎     993
# b_llslwq8z   2922:a21134e2940d (inactive) ████████████     1043
# b_n3gmq5yz   2581:c1a2afe566a4 (inactive) ████████████████ 1384
if [[ "$1" == "branches" ]]; then
    code="" # Base64-encoded Python script
    script="/tmp/hg-branches-$(date +%s).py"

    code+="IyEvdXNyL2Jpbi9lbnYgcHl0aG9uCiMgLSotIGNvZGluZzogdXRmLTggLSotCmltcG9ydCBzdWJwcm9j"
    code+="ZXNzLCBzeXMsIHJlCgpwcm9jID0gc3VicHJvY2Vzcy5Qb3BlbihbIi91c3IvbG9jYWwvYmluL2hnIGJy"
    code+="YW5jaGVzIC0tY2xvc2VkIC0tY29sb3I9bmV2ZXIiXSwKICAgIHN0ZG91dD1zdWJwcm9jZXNzLlBJUEUs"
    code+="CiAgICBzaGVsbD1UcnVlKQoob3V0cHV0LCBlcnJvcikgPSBwcm9jLmNvbW11bmljYXRlKCkKCmlmIGVy"
    code+="cm9yICE9IE5vbmU6CiAgICBwcmludCAiRXJyb3I6ICIsIGVycm9yCiAgICBzeXMuZXhpdCgxKQoKbG9u"
    code+="Z2VzdCA9IDAKbGluZXMgPSBvdXRwdXQuc3BsaXQoJ1xuJykKKGJyYW5jaGVzLCBoZWFkcywgY29tbWl0"
    code+="cykgPSAoW10sIFtdLCBbXSkKc3BhcmtzID0gWwogICAgdSJcdTAwMjAiLCAjIHNwYWNlCiAgICB1Ilx1"
    code+="MjU4RiIsICMg4paPCiAgICB1Ilx1MjU4RSIsICMg4paOCiAgICB1Ilx1MjU4RCIsICMg4paNCiAgICB1"
    code+="Ilx1MjU4QyIsICMg4paMCiAgICB1Ilx1MjU4QiIsICMg4paLCiAgICB1Ilx1MjU4QSIsICMg4paKCiAg"
    code+="ICB1Ilx1MjU4OSIsICMg4paJCiAgICB1Ilx1MjU4OCIsICMg4paICl0KCmZvciBsaW5lIGluIGxpbmVz"
    code+="OgogICAgaWYgbGluZSA9PSAiIjogY29udGludWUKICAgIG1hdGNoID0gcmUuc2VhcmNoKCcoXFMrKVxz"
    code+="KyhcZCspOihbMC05YS16XXsxMn0pJywgbGluZSkKICAgIGlmIG1hdGNoID09IE5vbmU6IGNvbnRpbnVl"
    code+="CiAgICBicmFuY2hlcy5hcHBlbmQobWF0Y2guZ3JvdXAoMSkpCiAgICBjb21taXRzLmFwcGVuZChtYXRj"
    code+="aC5ncm91cCgzKSkKICAgIGhlYWRzLmFwcGVuZChpbnQobWF0Y2guZ3JvdXAoMikpKQogICAgaWYgbGVu"
    code+="KG1hdGNoLmdyb3VwKDEpKSA+IGxvbmdlc3Q6CiAgICAgICAgbG9uZ2VzdCA9IGxlbihtYXRjaC5ncm91"
    code+="cCgxKSkKCmJzcGFya3MgPSBbXQpncmVhdGVzdCA9IG1heChoZWFkcykKcGVyY2hhciA9IDggIyBNYXhp"
    code+="bXVtIHNwYXJrIGJhcnMgcGVyIGNoYXJhY3RlcgptYXhpbXVtID0gMTYgIyBNYXhpbXVtIGNoYXJhY3Rl"
    code+="cnMgZm9yIDEwMCUKbWF4MTAwcCA9IHBlcmNoYXIgKiBtYXhpbXVtCmRpZmZzID0gWyhncmVhdGVzdCAt"
    code+="IGhlYWQpIGZvciBoZWFkIGluIGhlYWRzXQptYXhfZGlmZiA9IG1heChkaWZmcykKcmVhbF9wMTAwID0g"
    code+="WygoZGlmZiAqIDEwMCkgLyBtYXhfZGlmZikgZm9yIGRpZmYgaW4gZGlmZnNdOwpmYWtlX3AxMDAgPSBb"
    code+="KChwICogbWF4MTAwcCkgLyAxMDApIGZvciBwIGluIHJlYWxfcDEwMF0KCmZvciBmYWtlIGluIGZha2Vf"
    code+="cDEwMDoKICAgIHVuaXRzID0gKGZha2UgLyAocGVyY2hhciAqIDEuMCkpCiAgICBzdWVsbyA9IGludCh1"
    code+="bml0cykKICAgIGlmICh1bml0cyA9PSBzdWVsbyk6CiAgICAgICAgYnNwYXJrcy5hcHBlbmQodSJcdTI1"
    code+="ODgiICogc3VlbG8pCiAgICBlbHNlOgogICAgICAgIHJlc3QgPSBmYWtlIC0gKHN1ZWxvICogcGVyY2hh"
    code+="cikKICAgICAgICBmaXJzdCA9ICh1Ilx1MjU4OCIgKiBzdWVsbykKICAgICAgICB0cmFpbGluZyA9IHNw"
    code+="YXJrc1tyZXN0XQogICAgICAgIGJzcGFya3MuYXBwZW5kKGZpcnN0ICsgdHJhaWxpbmcpCgpmb3IgaWR4"
    code+="LCBoZWFkIGluIGVudW1lcmF0ZShoZWFkcyk6CiAgICBleHRyYSA9ICIiCiAgICBkaWZmID0gKGdyZWF0"
    code+="ZXN0IC0gaGVhZCkKICAgIGNvbW1pdCA9IGNvbW1pdHNbaWR4XQogICAgYnJhbmNoID0gYnJhbmNoZXNb"
    code+="aWR4XQogICAgc3BhY2VzID0gIlx4MjAiICogKGxvbmdlc3QgLSBsZW4oYnJhbmNoKSkKICAgIHdoaXRl"
    code+="YmFyID0gYnNwYXJrc1tpZHhdLmxqdXN0KG1heGltdW0pCiAgICBpZiBpZHggIT0gMDogY29tbWl0ICs9"
    code+="ICIgKGNsb3NlZCkgJXMgJWQiICUgKHdoaXRlYmFyLCBkaWZmKQogICAgcHJpbnQoIiVzJXMgJWQ6JXMi"
    code+="ICUgKGJyYW5jaCwgc3BhY2VzLCBoZWFkLCBjb21taXQpKQo="

    echo "$code" | base64 --decode 1> "$script"

    if [[ -e "$script" ]]; then
        /usr/bin/env python -- "$script"
        rm -f -- "$script" 2> /dev/null
        exit 0
    fi
fi

# Default to real Mercurial.
/usr/local/bin/hg "$@"
