#!/bin/bash
if [[ "$1" == "" ]] || [[ "$2" == "" ]] || [[ "$3" == "" ]] || [[ "$1" =~ "help" ]]; then
    S=$(basename "$0")
    echo "iTunes Music Downloader"
    echo
    echo "Download a video from the Internet using youtube-dl and extracts the audio"
    echo "before the file is imported to the local iTunes library. Some metadata is"
    echo "assigned to the file before the import action, things like the author's name"
    echo "and song title will be attached to the file via ID3v2 tags."
    echo
    echo "Usage: $S [video] [author] [title]"
    exit 2
fi

VIDEO="$1"
AUTHOR="${2:-Unknown}"
TITLE="${3:-Unknown}"
SYSTEM=$(uname -s)

if [[ "$SYSTEM" != "Darwin" ]]; then
    echo "Operation supported only on macOS"
    exit 1
fi

if ! command -v youtube-dl &> /dev/null; then
    echo "brew install youtube-dl"
    exit 1
fi

if ! command -v id3v2 &> /dev/null; then
    echo "brew install id3v2"
    exit 1
fi

echo "Downloading audio: ${VIDEO}"
youtube-dl --id --extract-audio --audio-format mp3 --audio-quality 0 -- "$VIDEO"

if echo "$VIDEO" | grep -q "v="; then
    VIDEO=$(echo "$VIDEO" | cut -d "=" -f2 | cut -d "&" -f1)
    echo "Extracting unique ID: ${VIDEO}"
fi

if [[ ! -e "${VIDEO}.mp3" ]]; then
    echo "File does not exists: ${VIDEO}.mp3"
    exit 1
fi

echo "Setting title: \"${TITLE}\""
echo "Setting author: \"${AUTHOR}\""
id3v2 -t "$TITLE" -a "$AUTHOR" "${VIDEO}.mp3"

echo "Importing to iTunes"
open -a iTunes -g "${VIDEO}.mp3"

echo -n "Deleting... "
sleep 2 && rm -- "${VIDEO}.mp3"
echo "OK"
