#!/bin/bash
BINARY="/Applications/Meld.app/Contents/MacOS/Meld"

if [[ ! -e "$BINARY" ]]; then
    echo "Meld for Mac is not installed"
    exit 1
fi

if [[ "$1" == "" ]]; then
    echo "Usage: meld [old-file] [new-file] [optional]"
    exit 2
fi

if [[ "$3" == "" ]]; then
    # Compare two resources (files or directories)
    eval "$BINARY \"$1\" \"$2\" 2> /dev/null"
    exit 0
fi

# Compare three resources (files or directories)
eval "$BINARY \"$1\" \"$2\" \"$3\""
