#!/bin/bash
# Execute PHPUnit with smart test suite detection.
if echo "$@" | grep -q -- '^--filter .*::.*'; then
    PARAMS="$@" # Get original command arguments.
    PARAMS=$(echo "$PARAMS" | sed 's;--filter ;tests/;g')
    PARAMS=$(echo "$PARAMS" | sed 's;::;\.php --filter ;')
    /usr/local/bin/phpunit "$PARAMS"
    exit $?
fi

/usr/local/bin/phpunit "$@"
