#!/bin/bash
# Execute custom PHPCode_Sniffer coding standard.
STANDARD="${HOME}/.psr99.xml"
RULESET=(
    '<?xml version="1.0"?>'
    '<ruleset name="PSR99">'
    '  <description>PSR2 without some unnecessary rules.</description>'
    '  <exclude-pattern>*.min.css</exclude-pattern>'
    '  <exclude-pattern>*.min.js</exclude-pattern>'
    '  <rule ref="PSR2">'
    '    <exclude name="Generic.Files.LineLength"/>'
    '    <exclude name="Internal.Tokenizer.Exception"/>'
    '    <exclude name="PSR1.Classes.ClassDeclaration.MissingNamespace" />'
    '    <exclude name="PSR1.Files.SideEffects.FoundWithSymbols" />'
    '  </rule>'
    '  <rule ref="Internal.NoCodeFound">'
    '    <severity>0</severity>'
    '  </rule>'
    '</ruleset>'
)

if command -v phpcs &> /dev/null; then
    if [[ ! -e "$STANDARD" ]]; then
        for LINE in "${RULESET[@]}"; do
            echo "$LINE" 1>> "$STANDARD"
        done
    fi

    /usr/bin/env phpcs -w \
    --standard="$STANDARD" \
    --report-width=150 \
    --report=full \
    --colors "$@"
fi
