#!/bin/bash
# Execute custom PHPCode_Sniffer coding standard.
ruleset=''
ruleset+='<?xml version="1.0"?>'
ruleset+='<ruleset name="PSR99">'
ruleset+='  <description>PSR2 without some unnecessary rules.</description>'
ruleset+='  <rule ref="PSR2">'
ruleset+='    <exclude name="Generic.Files.LineLength"/>'
ruleset+='    <exclude name="PSR1.Classes.ClassDeclaration.MissingNamespace" />'
ruleset+='    <exclude name="PSR1.Files.SideEffects.FoundWithSymbols" />'
ruleset+='  </rule>'
ruleset+='  <rule ref="Internal.NoCodeFound">'
ruleset+='    <severity>0</severity>'
ruleset+='  </rule>'
ruleset+='</ruleset>'
standard="$HOME/.psr99.xml"

if [[ ! -e "$standard" ]]; then
    echo "$ruleset" 1> "$standard"
fi

if command -v phpcs &> /dev/null; then
    /usr/bin/env phpcs -w -l \
    --standard="$standard" \
    --report-width=150 \
    --report=full \
    --colors "$@"
fi
