#!/bin/bash
IFS=$'\n'

function report() {
    INDEX=0
    DATES=($(git log | grep "Date"))
    TOTAL=$(git log | grep -c "Date")
    HASHES=($(git log | grep "^commit" | awk '{print $2}'))
    AUTHORS=($(git log | grep "^Author" | cut -d: -f2))
    ORIGINURL=$(git config --get "remote.origin.url")
    echo "Repository: ${ORIGINURL}"
    for FULLDATE in "${DATES[@]}"; do
        DATE="${FULLDATE:8:100}"
        UNIQUE="${HASHES[INDEX]}"
        AUTHOR="${AUTHORS[INDEX]}"
        echo "${UNIQUE} >>> ${DATE} -${AUTHOR}"
        INDEX=$((INDEX+1))
    done
    echo "Total commits: ${TOTAL}"
}

COMMIT="$1" # Full commit hash.
COMDATE="${2}T09:00:00" # yyyy-mm-dd

if [[ "$COMMIT" == "" ]] || [[ "$COMMIT" =~ help ]]; then
    SCRIPT=$(echo "$0" | rev | cut -d/ -f1 | rev)
    echo "Repository Status"
    echo "  https://cixtor.com/"
    echo "  https://en.wikipedia.org/wiki/Git"
    echo "  https://github.com/cixtor/dotfiles/.bin/"
    echo "Usage:"
    echo "  ${SCRIPT} [commit] [yyyy-mm-dd]       Changes commit date in a commit"
    echo "  ${SCRIPT} -status [username] [pages]  Checks non-synced repositories"
    echo "  ${SCRIPT} -dates                      Prints all commit dates"
    exit 2
fi

if [[ "$1" == "-status" ]]; then
    TOTAL=0
    CHECKED=0
    COUNTER="100"
    UNTILTHISPAGE="${3:-1}"
    USERNAME="${2:-cixtor}"
    NOCHANGES="490743d5fc30afe6422f2b593c9cbaed"

    # 00000000  4f 6e 20 62 72 61 6e 63  68 20 6d 61 73 74 65 72  |On branch master|
    # 00000010  0a 59 6f 75 72 20 62 72  61 6e 63 68 20 69 73 20  |.Your branch is |
    # 00000020  75 70 20 74 6f 20 64 61  74 65 20 77 69 74 68 20  |up to date with |
    # 00000030  27 6f 72 69 67 69 6e 2f  6d 61 73 74 65 72 27 2e  |'origin/master'.|
    # 00000040  0a 0a 6e 6f 74 68 69 6e  67 20 74 6f 20 63 6f 6d  |..nothing to com|
    # 00000050  6d 69 74 2c 20 77 6f 72  6b 69 6e 67 20 74 72 65  |mit, working tre|
    # 00000060  65 20 63 6c 65 61 6e 0a                           |e clean.|
    # 00000068

    echo ">> Author: https://github.com/${USERNAME}"
    echo ">> Checking repositories in ${UNTILTHISPAGE} page(s)"

    for ((PAGE=1; PAGE<=UNTILTHISPAGE; PAGE++)); do
        PAGEURL="https://github.com/${USERNAME}?tab=repositories&page=${PAGE}"

        if [[ "$PAGE" -eq 1 ]]; then
            # First page doesn't needs the page parameter.
            PAGEURL=$(echo "$PAGEURL" | cut -d "&" -f1)
        fi

        RESPONSE=$(
            curl -X GET --url "$PAGEURL" \
            -H "Mozilla/5.0 (KHTML, like Gecko) Safari/537.36" \
            -H "Accept: text/html,application/xhtml+xml,application/xml" \
            --silent
        )

        for REPOSITORY in $(echo "$RESPONSE" | grep "codeRepository" | cut -d '"' -f2); do
            COUNTER=$((COUNTER + 1))
            PROJECT=$(echo "$REPOSITORY" | cut -d "/" -f3)
            DIRECTORY="${HOME}/Projects/${PROJECT}"
            TOTAL=$((TOTAL+1))

            # Dot.files are usually in the home directory.
            if [[ "$PROJECT" == "dotfiles" ]]; then
                DIRECTORY="$HOME"
            fi

            if [[ ! -e "$DIRECTORY" ]]; then
                printf "   \x1b[48;5;007m  \x1b[0m %s\x0a" "$DIRECTORY"
                continue
            fi

            # Check if the repository has no changes.
            CHECKED=$((CHECKED+1))
            GITSTATUS=$(git -C "$DIRECTORY" status)
            CHECKSUM=$(echo "$GITSTATUS" | /sbin/md5)

            if [[ "$CHECKSUM" == "$NOCHANGES" ]]; then
                printf "   \x1b[48;5;010m  \x1b[0m %s\x0a" "$DIRECTORY"
                continue
            fi

            # Determine the number of commits to push upstream.
            if echo "$GITSTATUS" | grep -q "branch is ahead"; then
                printf "\x20\x20" # column separator.
                HOWMANY=$(echo "$GITSTATUS" | grep "ahead" | cut -d "'" -f3)
                HOWMANY=$(echo "$HOWMANY" | rev | cut -c2-100 | rev)
                printf " \x1b[48;5;014m  \x1b[0m %s" "$DIRECTORY"
                printf " \x1b[0;96m(ahead%s)\x1b[0m\x0a" "$HOWMANY"
                continue
            fi

            # Report additional changes including added, modified, and untracked files.
            printf "   \x1b[48;5;011m  \x1b[0m %s\x0a" "$DIRECTORY"
        done
    done

    echo ">> Checked ${CHECKED} out of ${TOTAL} repositories"
    echo ">> Color Details:"
    echo -e "   \x1b[48;5;007m  \x1b[0m Repository is not in the disk"
    echo -e "   \x1b[48;5;010m  \x1b[0m Repository is synced with remote"
    echo -e "   \x1b[48;5;014m  \x1b[0m There are changes to push live"
    echo -e "   \x1b[48;5;011m  \x1b[0m There are uncommitted changes"
    exit 0
fi

if [[ "$1" == "-dates" ]]; then report; exit 0; fi

git filter-branch -f --env-filter \
"if [ \$GIT_COMMIT == $COMMIT ]; then
export GIT_AUTHOR_DATE='$COMDATE'
export GIT_COMMITTER_DATE='$COMDATE'
fi"

report
