#!/bin/bash
# Display information about an SSL certificate.
if [[ "$1" == "" ]] || [[ "$1" =~ help ]]; then
    SCRIPT=$(basename "$0")
    echo "SSL Certificate Client"
    echo "Usage:"
    echo "  $SCRIPT [host]       Displays SSL certificate information"
    echo "  $SCRIPT [host] -exp  Displays the expiration of a certificate"
    exit 2
fi

ACTION="${2:-none}"
DOMAIN="${1:-example.com}"

if [[ "$ACTION" == "-exp" ]]; then
    echo "domain=${DOMAIN}"; echo \
    | openssl s_client -connect "${DOMAIN}:443" 2> /dev/null \
    | openssl x509 -dates -noout
    exit
fi

echo | openssl s_client -connect "${DOMAIN}:443"
