#!/bin/bash
# Display information about an SSL certificate.
if [[ "$1" == "" ]] || [[ "$1" =~ help ]]; then
    SCRIPT=$(basename "$0")
    echo "SSL Certificate Client"
    echo "Usage:"
    echo "  $SCRIPT [host]       Displays SSL certificate information"
    exit 2
fi

ACTION="${2:-none}"
DOMAIN="${1:-example.com}"

echo | openssl s_client -connect "${DOMAIN}:443"
