#!/bin/bash
function update_go_tool() {
	PACKAGE="$1"

	if [[ "$1" == "" ]]; then
		return
	fi

	FILENAME=$(echo "$PACKAGE" | rev | cut -d/ -f1 | rev)
	FILEPATH=$(command -v "$FILENAME")

	if [[ ! -e "$FILEPATH" ]]; then
		echo "\`${FILEPATH}\` does not exists"
		return
	fi

	echo -n "Updating ........... ${FILENAME}…"
	OLDVERSION=$(shasum "$FILEPATH" | cut -c1-8)

	go get -u "$PACKAGE"
	NEWVERSION=$(shasum "$FILEPATH" | cut -c1-8)
	echo -e "\r${OLDVERSION} -> ${NEWVERSION} ${PACKAGE}"
}

PACKAGES=(
	"github.com/cixtor/powergoline"
	"github.com/cixtor/emailgetter"
	"github.com/cixtor/fileserver"
	"github.com/cixtor/refactor"
	"github.com/cixtor/similardiff"
	"github.com/cixtor/slackcli"
	"github.com/cixtor/sparkline"
	"github.com/cixtor/strconv"
	"github.com/cixtor/webttfb"
	"github.com/cixtor/wptickets"
	"golang.org/x/tools/cmd/gopls"
	"github.com/tsenart/deadcode"
	"github.com/mibk/dupl"
	"github.com/kisielk/errcheck"
	"github.com/jgautheron/goconst/cmd/goconst"
	"github.com/alecthomas/gocyclo"
	"golang.org/x/tools/cmd/goimports"
	"golang.org/x/lint/golint"
	"github.com/securego/gosec/cmd/gosec"
	"golang.org/x/tools/cmd/gotype"
	"github.com/gordonklaus/ineffassign"
	"github.com/walle/lll"
	"github.com/mdempsky/maligned"
	"github.com/client9/misspell/cmd/misspell"
	"github.com/alexkohler/nakedret"
	"github.com/stripe/safesql"
	"honnef.co/go/tools/cmd/staticcheck"
	"gitlab.com/opennota/check/cmd/structcheck"
	"github.com/mdempsky/unconvert"
	"github.com/mvdan/unparam"
	"gitlab.com/opennota/check/cmd/varcheck"
)

for PACKAGE in "${PACKAGES[@]}" ; do
	update_go_tool "$PACKAGE"
done
